<?php
$this->htmlElement('body')->appendAttribute('class', 'page');
$this->pageTitle($page->title(), 2);
$showPagePagination = $this->siteSetting('show_page_pagination', true);
?>

<?php
$nav = $site->publicNav();
$container = $nav->getContainer();
$activePage = $nav->findActive($container);
if ($activePage) :
?>
  <?php if ($activePage['depth'] !== 0) : ?>
    <nav class="breadcrumbs"><?php echo $nav->breadcrumbs(); ?></nav>
  <?php endif; ?>
<?php endif; ?>

<?php /* if ($activePage) : ?>
  <?php if ($this->displayNavigation && $activePage['page']->hasPages()) : ?>
    <nav class="sub-menu"><?php echo $nav->menu()->renderSubMenu(); ?></nav>
  <?php endif; ?>
<?php endif; */ ?>

<?php $this->trigger('view.show.before'); ?>
<div class="blocks py-3 py-md-5">

    <?php echo $this->content; ?>

</div>
<script>
document.addEventListener('DOMContentLoaded', function() {
    let images = document.querySelectorAll('.media-render.file a img');
    images.forEach(function(image) {
        let anchorTitle = image.parentNode.getAttribute('title');
        if (anchorTitle && image.getAttribute('alt') === '') {
            image.setAttribute('alt', anchorTitle);
        }
        image.classList.add('img-fluid');
    });
});
</script>


<?php $this->trigger('view.show.after'); ?>
<?php if ($showPagePagination) : ?>
  <?php echo $this->sitePagePagination(); ?>
<?php endif; ?>