<div class="<?php echo $this->alignmentClass . ' ' . $this->thumbnailType; ?> file row">

    <div class="attachments col">
        <?php foreach ($this->attachments as $attachment) : ?>
            <div class="item resource block-layout-file-attachment">
                <?php
                $item = $attachment->item();
                if ($item) :
                ?>
                    <?php $showTitleOption = $this->showTitleOption; ?>
                    <?php if ($showTitleOption == 'item_title') : ?>
                        <h6><?php echo $item->link($item->displayTitle()); ?></h6>
                    <?php elseif ($showTitleOption == 'file_name') : ?>
                        <h3><?php echo $media->displayTitle(); ?></h3>
                    <?php endif; ?>
                    <?php
                    $media = $attachment->media() ?: $item->primaryMedia();
                    if ($media) :
                        echo $media->render([
                            'thumbnailType' => $thumbnailType,
                            'link' => $link,
                        ]);
                    endif;
                    ?>

                <?php endif; ?>


            </div>
        <?php endforeach; ?>
    </div>
    <?php
    $caption = $attachment->caption();
    if ($caption) :
    ?>
        <div class="caption col"><?php echo $caption; ?></div>
    <?php endif; ?>
</div>