<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->appendAttribute('lang', $this->lang())->appendAttribute('class', 'h-100');
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($site->title())->setSeparator(' · ');
$this->headLink(['rel' => 'icon', 'type' => 'image/png', 'href' => $this->assetUrl('img/favicon.png')]);
$this->headLink(['rel' => 'icon', 'type' => 'image/svg+xml', 'href' => $this->assetUrl('img/favicon.svg')], 'PREPEND')
  ->prependStylesheet($this->assetUrl('css/style.css'))
  ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.6.0/nouislider.css', 'screen', null, ['integrity' => 'sha512-MKxcSu/LDtbIYHBNAWUQwfB3iVoG9xeMCm32QV5hZ/9lFaQZJVaXfz9aFa0IZExWzCpm7OWvp9zq9gVip/nLMg==', 'crossorigin' => 'anonymous'])
  ->prependStylesheet('https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/all.min.css', 'screen', null, ['integrity' => 'sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4=', 'crossorigin' => 'anonymous'])
  ->prependStylesheet('https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css', 'screen', null, ['integrity' => 'sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU', 'crossorigin' => 'anonymous']);
$this->headScript()
  ->prependFile($this->assetUrl('js/advanced-search.js', 'Omeka'))
  ->prependFile($this->assetUrl('js/theme.js'))
  ->prependFile($this->assetUrl('js/global.js', 'Omeka'))
  ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.6.0/nouislider.min.js', 'text/javascript', ['integrity' => 'sha512-1mDhG//LAjM3pLXCJyaA+4c+h5qmMoTc7IuJyuNNPaakrWT9rVTxICK4tIizf7YwJsXgDC2JP74PGCc7qxLAHw==', 'crossorigin' => 'anonymous'])
  ->prependFile('https://unpkg.com/infinite-scroll@4.0.1/dist/infinite-scroll.pkgd.min.js', 'text/javascript')
  ->prependFile('https://cdn.jsdelivr.net/npm/corejs-typeahead@1.3.1/dist/typeahead.bundle.min.js', 'text/javascript', ['integrity' => 'sha256-xZuy7z/QR1H5FKCYUbRDj4yvcyMEyVIg4iQUhs8MI+w=', 'crossorigin' => 'anonymous'])
  ->prependFile('https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js', 'text/javascript', ['integrity' => 'sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ', 'crossorigin' => 'anonymous'])
  ->prependFile('https://code.jquery.com/jquery-3.6.0.min.js', 'text/javascript', ['integrity' => 'sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=', 'crossorigin' => 'anonymous']);
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>

<head>

  <?php echo $this->headMeta(); ?>
  <?php echo $this->headTitle(); ?>
  <?php echo $this->headLink(); ?>
  <?php echo $this->headStyle(); ?>
  <?php echo $this->headScript(); ?>
</head>

<?php echo $this->htmlElement('body')->appendAttribute('class', ''); ?>
<a class="visually-hidden-focusable" href="#content">
  <?php echo $this->translate('Skip to main content'); ?>
</a>
<?php echo $userBar; ?>
<header>
  <div class="container pt-5 pb-2 d-none d-md-block">
    <div class="row justify-content-center">
      <div class="col-auto">
        <a href="/" class="logo text-dark text-decoration-none">
          <h1 class="visually-hidden"><?php echo $escape($site->title()); ?></h1>
          <img width="7000" src="<?php echo $this->assetUrl('img/ruzake-gila-top-logo.svg'); ?>" title="Home" alt="Ruzake Gila Logo">
        </a>
      </div>
    </div>
  </div>
  <nav class="navbar navbar-expand-md navbar-light">
    <div class="container-fluid">
      <a class="navbar-brand  d-md-none" href="<?php echo $site->url(); ?>">
        <h1 class="h5 d-inline">Ružake Gila</h1>
        <img width="15" src="<?php echo $this->assetUrl('img/ruza-face-logo.svg'); ?>" title="Home" alt="Ruzake Gila Logo">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <?php echo $site->publicNav()->menu()->renderPartialWithParams(['site' => $site,], null, 'common/bootstrap-navigation.phtml'); ?>
      </div>
    </div>
  </nav>
</header>
<?php $path = $_SERVER["REQUEST_URI"];?>

<? if ($path == "/s/ruzakegila/page/willkommen"): ?>
<div class="carousel-wrapper container-fluid">
  <div class="carousel slide" data-bs-ride="carousel" id="carouselWelcomePage">
    <div class="carousel-inner">
      <div class="carousel-item active"><a href="/s/ruzakegila/item/372" target="_blank" title="1993 - Donauinsel - © mdw – University of Music and Performing Arts Vienna"><img alt="Donauinsel - 1" class="d-block w-100" draggable="true" src="/files/original/ca219501581361404e5d9fc54ad7077ea502b49c.jpg" /> </a></div>

      <div class="carousel-item"><a href="/s/ruzakegila/item/476" target="_blank" title="1991 - Amerlinghaus - © mdw – University of Music and Performing Arts Vienna"><img alt="Amerlinghaus - 2" class="d-block w-100" draggable="false" src="/files/original/29d309b678ca87344b28d5f3716ed6305a6a3ce8.jpg" /> </a></div>

      <div class="carousel-item"><a href="/s/ruzakegila/item/370" target="_blank" title="1993 - Donauinsel - © mdw – University of Music and Performing Arts Vienna"><img alt="Donauinsel - 3 " class="d-block w-100" draggable="false" src="/files/original/0504d780c313cc69fa6bdea92d11499caac79f8d.jpg" /> </a></div>

      <div class="carousel-item"><a href="/s/ruzakegila/item/362" target="_blank" title="1991 - Amerlinghaus - © mdw – University of Music and Performing Arts Vienna"><img alt="Amerlinghaus - 4" class="d-block w-100" draggable="false" src="/files/original/4199696bc197cc9391a28181ab7307874cab2ec3.jpg" /> </a></div>
    </div>
    <button class="carousel-control-prev" data-bs-slide="prev" data-bs-target="#carouselWelcomePage" title="Previous" type="button"><span aria-hidden="true" class="carousel-control-prev-icon">&nbsp;</span> <span class="visually-hidden">Previous</span></button><button class="carousel-control-next" data-bs-slide="next" data-bs-target="#carouselWelcomePage" title="Next" type="button"><span aria-hidden="true" class="carousel-control-next-icon">&nbsp;</span> <span class="visually-hidden">Next</span></button>
  </div>
</div>
<? endif; ?>


<div class="container" id="content" role="main">
  <?php echo $this->content; ?>
</div>

<footer class="footer mt-auto py-3 py-md-5 border-top border-light">
  <div class="container text-center">
    <div class="row justify-content-center">
      <div class="col-md-12">
        <a href="https://www.mdw.ac.at">
          <img class="mx-3" src="<?php echo $this->assetUrl('img/mdw-logo.png'); ?>" alt="MDW Logo" id="mdw-logo" height="100">
        </a>
        <a href="https://www.mdw.ac.at/musicandminorities/">
          <img class="mx-3" src="<?php echo $this->assetUrl('img/mm-logo.svg'); ?>" alt="Music & Minorities Logo" id="mm-logo" height="100">
        </a>
        <a href="https://www.fwf.ac.at/" title="Funded by the Austrian Science Fund (FWF): Z 352-G26">
          <img class="mx-3" src="<?php echo $this->assetUrl('img/fwf-logo.svg'); ?>" alt="Funded by the Austrian Science Fund (FWF): Z 352-G26" id="fwf-logo" height="100">
        </a>
        <!-- <p class="small">
          <?php echo date("Y"); ?> mdw – Universität für Musik und darstellende Kunst Wien
          <br>Anton-von-Webern-Platz 1
          <br>1030 Wien
          <br>E-Mail: <a href="mailto:mmrc@mdw.ac.at">mmrc@mdw.ac.at</a>
        </p> -->
        <p class="mt-3">
          <a href="https://www.mdw.ac.at/datenschutz/">Datenschutzerklärung</a>
          |
          <a href="https://www.mdw.ac.at/impressum/">Impressum</a>
        </p>
      </div>
    </div>
  </div>
</footer>
</body>

</html>